### ISSUE TITLE
Add default sort order to tv/schedules

### ISSUE THREAD

**Issue by mymatenige** [MythTV/mythweb#36]
When a user navigates to /tv/schedules the very first time the results aren't ordered. I believe that it would be good for them to be ordered by title on first.

Suggested fix in pull request #48.

Exists in master, fixes/31, fixes/30 and maybe others.

**Comment by JohnLBergqvist** [comment]
The behaviour is to order the scheduled by the default `recordid` column, which auto-increments, thus by default, your schedules are ordered with the earliest created at the top, and most-recent at the bottom, which IMO is a sensible default, but of course others may disagree. However the I believe the default order in mythweb should correspond to the default order used in the frontend.
