### ISSUE TITLE
Add support for PHP 8.x

### ISSUE THREAD

**Issue by mymatenige** [MythTV/mythweb#63]
Of course it's well known that MythWeb doesn't support PHP 8.x. In response to this I've seen comments suggesting that pull requests would be considered.  I've worked through all of the issues I've identified and created pull request #62.  MythWeb is now working for me on 8.0 and I believe it will also work on 8.1.  Please consider my pull request.

**Comment by mymatenige** [comment]
Closing for now.  Found an issue with my pull request.

**Comment by bennettpeter** [comment]
Fixed in #64
