### ISSUE TITLE
Unable to open mythweb if mythmusic has never been used

### ISSUE THREAD

**Issue by TownCube** [MythTV/mythweb#83]
The [PHP docs](https://www.php.net/manual/en/mysqli-driver.report-mode.php) report:

> As of PHP 8.1.0, the default setting is MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT. Previously, it was MYSQLI_REPORT_OFF. 

This is breaking MythWeb from starting if you don't use mythmusic as [the init check](https://github.com/MythTV/mythweb/blob/e533158f76739fa813a18655ccd71a6ec2b535de/modules/music/init.php#L15) now throws this:

```
PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'mythconverg.music_songs' doesn't exist in
 /usr/share/mythweb/classes/Database/Query/mysqlicompat.php:68
Stack trace:
#0 /usr/share/mythweb/classes/Database/Query/mysqlicompat.php(68): mysqli_query()
#1 /usr/share/mythweb/classes/Database.php(263): Database_Query_mysqlicompat->execute()
#2 /usr/share/mythweb/classes/Database.php(326): Database->query()
#3 /usr/share/mythweb/modules/music/init.php(15): Database->query_col()
#4 /usr/share/mythweb/classes/Modules.php(30): require_once('...')
#5 /usr/share/mythweb/classes/Modules.php(50): Modules::load()
#6 /usr/share/mythweb/mythweb.php(30): Modules::getModule()
```

Initially I was thinking you could switch to looking up if the table existed in the information_schema which would solve these checks in the init modules however it wouldn't solve [this case](https://github.com/MythTV/mythweb/blob/e020a3ef5e157855960d41914c7a00214f4a2e27/modules/tv/schedules_custom.php#L130-L138) where the user's custom SQL needs to be attempted and the result reported back.

Options:

1. Restore previous behaviour by running `mysqli_report(MYSQLI_REPORT_OFF);` somewhere high up (eg. on connect)
2. Add `try...catch` around the [mysqli_query](https://github.com/MythTV/mythweb/blob/6a0b01396b58415a83b3cd3229641c4813ccc9b3/classes/Database/Query/mysql.php#L66) call and handle based on the `$db->fatal_errors` setting
3. Remove the enable/disable fatal_errors functionality completely and handle the exceptions locally as required.

Happy to help with a pull request once an option is decided on,

**Comment by mymatenige** [comment]
@stuarta I've created a quick-n-dirty pull request to keep MythWeb working with PHP 8.1.0.  Any chance that it can be reviewed and merged?

**Comment by mymatenige** [comment]
This can now be closed as the pull request has been merged.
